# Default values for gerrit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/gerritcodereview/gerrit
  tag: 2.15.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30088
  - name: ssh
    port: 29418
    targetPort: 29418

persistence:
  enabled: true
  volumes:
  - name: git
    size: 1Gi
    storageClass: csi-sc-cinderplugin
  - name: etc
    size: 1Gi
  - name: index
    storageClass: csi-sc-cinderplugin
    size: 1Gi
  - name: cache
    size: 2Gi
    storageClass: csi-sc-cinderplugin
  - name: data
    size: 2Gi
    storageClass: csi-sc-cinderplugin
  - name: db
    size: 2Gi
    storageClass: csi-sc-cinderplugin

config:
  auth:
    type: ldap
    server:
    accountBase:
    groupBase:
  index:
    type: LUCENE

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}
